env:
  browser: true
  es6: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - prettier/react
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - prettier
rules:
  no-underscore-dangle: 0
  react/prop-types: off
  import/prefer-default-export: off # airbnb default: 'error'
  react/prefer-stateless-function: warn # airbnb default: 'error'

  # Enforce a defaultProps definition for every prop that is not a required prop
  # reason: function composition over default props
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md
  react/require-default-props: off # airbnb default: 'error'

  ### Removed rules
  # no longer defined
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/label-has-associated-control: off

  # was complaining about inline snapshots
  no-irregular-whitespace:
    - off
  indent: 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-redeclare: "error"
